name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Puppeteer Container
      uses: ianwalter/puppeteer@v2.0.0
    - name: npm install, npm run server
      run: |
        npm ci
        npm run server &
      env:
        CI: true
    - name: Test Robot
      run: |
        cd packages/robot
        npm test
        npm run bundlesize
